// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcfndtwjamrrmhfgbrdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjZm5kdHdqYW1ycm1oZmdicmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTcyMjAsImV4cCI6MjA3MjQ5MzIyMH0.EL21FEKrlGIcy-UkZ245_clxwVVVKqIbsT-XEPxJjqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});